# Dev stage
FROM node:15.13.0-alpine3.13

RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python && rm -rf /var/cache/apk/*

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install

ADD ./src ./src