name: 'Heroku Deployment'

on:
  registry_package:
    types: [published, updated]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Docker Image to Heroku App
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          dockerfile_path: './Dockerfile.prod' # set the path to the folder wher the Dokerfile is located
          options: '' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web